// Code generated by github.com/DIMO-Network/model-garage.
package teslatelem

// This file is automatically populated with conversion functions for each field of the model struct.
// any conversion functions already defined in this package will be coppied through.
// note: DO NOT mutate the orginalDoc parameter which is shared between all conversion functions.

// ToChassisAxleRow1WheelLeftTirePressure0 converts data from field 'TpmsPressureFl' of type Value_StringValue to 'Vehicle.Chassis.Axle.Row1.Wheel.Left.Tire.Pressure' of type float64.
// Vehicle.Chassis.Axle.Row1.Wheel.Left.Tire.Pressure: Tire pressure in kilo-Pascal.
// Unit: 'kPa'
func ToChassisAxleRow1WheelLeftTirePressure0(originalDoc []byte, val Value_StringValue) (float64, error) {
	panic("not implemented")
}

// ToChassisAxleRow1WheelRightTirePressure0 converts data from field 'TpmsPressureFr' of type Value_StringValue to 'Vehicle.Chassis.Axle.Row1.Wheel.Right.Tire.Pressure' of type float64.
// Vehicle.Chassis.Axle.Row1.Wheel.Right.Tire.Pressure: Tire pressure in kilo-Pascal.
// Unit: 'kPa'
func ToChassisAxleRow1WheelRightTirePressure0(originalDoc []byte, val Value_StringValue) (float64, error) {
	panic("not implemented")
}

// ToChassisAxleRow2WheelLeftTirePressure0 converts data from field 'TpmsPressureRl' of type Value_StringValue to 'Vehicle.Chassis.Axle.Row2.Wheel.Left.Tire.Pressure' of type float64.
// Vehicle.Chassis.Axle.Row2.Wheel.Left.Tire.Pressure: Tire pressure in kilo-Pascal.
// Unit: 'kPa'
func ToChassisAxleRow2WheelLeftTirePressure0(originalDoc []byte, val Value_StringValue) (float64, error) {
	panic("not implemented")
}

// ToChassisAxleRow2WheelRightTirePressure0 converts data from field 'TpmsPressureRr' of type Value_StringValue to 'Vehicle.Chassis.Axle.Row2.Wheel.Right.Tire.Pressure' of type float64.
// Vehicle.Chassis.Axle.Row2.Wheel.Right.Tire.Pressure: Tire pressure in kilo-Pascal.
// Unit: 'kPa'
func ToChassisAxleRow2WheelRightTirePressure0(originalDoc []byte, val Value_StringValue) (float64, error) {
	panic("not implemented")
}
