// Code generated by "model-garage" DO NOT EDIT.
package vss

const (
	// FieldVehicleChassisAxleRow1WheelLeftTirePressure Tire pressure in kilo-Pascal.
	FieldVehicleChassisAxleRow1WheelLeftTirePressure = "Vehicle_Chassis_Axle_Row1_Wheel_Left_Tire_Pressure"
	// FieldVehicleChassisAxleRow1WheelRightTirePressure Tire pressure in kilo-Pascal.
	FieldVehicleChassisAxleRow1WheelRightTirePressure = "Vehicle_Chassis_Axle_Row1_Wheel_Right_Tire_Pressure"
	// FieldVehicleChassisAxleRow2WheelLeftTirePressure Tire pressure in kilo-Pascal.
	FieldVehicleChassisAxleRow2WheelLeftTirePressure = "Vehicle_Chassis_Axle_Row2_Wheel_Left_Tire_Pressure"
	// FieldVehicleChassisAxleRow2WheelRightTirePressure Tire pressure in kilo-Pascal.
	FieldVehicleChassisAxleRow2WheelRightTirePressure = "Vehicle_Chassis_Axle_Row2_Wheel_Right_Tire_Pressure"
	// FieldVehicleCurrentLocationAltitude Current altitude relative to WGS 84 reference ellipsoid, as measured at the position of GNSS receiver antenna.
	FieldVehicleCurrentLocationAltitude = "Vehicle_CurrentLocation_Altitude"
	// FieldVehicleCurrentLocationLatitude Current latitude of vehicle in WGS 84 geodetic coordinates, as measured at the position of GNSS receiver antenna.
	FieldVehicleCurrentLocationLatitude = "Vehicle_CurrentLocation_Latitude"
	// FieldVehicleCurrentLocationLongitude Current longitude of vehicle in WGS 84 geodetic coordinates, as measured at the position of GNSS receiver antenna.
	FieldVehicleCurrentLocationLongitude = "Vehicle_CurrentLocation_Longitude"
	// FieldVehicleCurrentLocationTimestamp Timestamp from GNSS system for current location, formatted according to ISO 8601 with UTC time zone.
	FieldVehicleCurrentLocationTimestamp = "Vehicle_CurrentLocation_Timestamp"
	// FieldVehicleExteriorAirTemperature Air temperature outside the vehicle.
	FieldVehicleExteriorAirTemperature = "Vehicle_Exterior_AirTemperature"
	// FieldVehicleLowVoltageBatteryCurrentVoltage Current Voltage of the low voltage battery.
	FieldVehicleLowVoltageBatteryCurrentVoltage = "Vehicle_LowVoltageBattery_CurrentVoltage"
	// FieldVehicleOBDBarometricPressure PID 33 - Barometric pressure
	FieldVehicleOBDBarometricPressure = "Vehicle_OBD_BarometricPressure"
	// FieldVehicleOBDEngineLoad PID 04 - Engine load in percent - 0 = no load, 100 = full load
	FieldVehicleOBDEngineLoad = "Vehicle_OBD_EngineLoad"
	// FieldVehicleOBDIntakeTemp PID 0F - Intake temperature
	FieldVehicleOBDIntakeTemp = "Vehicle_OBD_IntakeTemp"
	// FieldVehicleOBDRunTime PID 1F - Engine run time
	FieldVehicleOBDRunTime = "Vehicle_OBD_RunTime"
	// FieldVehiclePowertrainCombustionEngineECT Engine coolant temperature.
	FieldVehiclePowertrainCombustionEngineECT = "Vehicle_Powertrain_CombustionEngine_ECT"
	// FieldVehiclePowertrainCombustionEngineEngineOilLevel Engine oil level.
	FieldVehiclePowertrainCombustionEngineEngineOilLevel = "Vehicle_Powertrain_CombustionEngine_EngineOilLevel"
	// FieldVehiclePowertrainCombustionEngineSpeed Engine speed measured as rotations per minute.
	FieldVehiclePowertrainCombustionEngineSpeed = "Vehicle_Powertrain_CombustionEngine_Speed"
	// FieldVehiclePowertrainCombustionEngineTPS Current throttle position.
	FieldVehiclePowertrainCombustionEngineTPS = "Vehicle_Powertrain_CombustionEngine_TPS"
	// FieldVehiclePowertrainFuelSystemAbsoluteLevel Current available fuel in the fuel tank expressed in liters.
	FieldVehiclePowertrainFuelSystemAbsoluteLevel = "Vehicle_Powertrain_FuelSystem_AbsoluteLevel"
	// FieldVehiclePowertrainFuelSystemSupportedFuelTypes High level information of fuel types supported
	FieldVehiclePowertrainFuelSystemSupportedFuelTypes = "Vehicle_Powertrain_FuelSystem_SupportedFuelTypes"
	// FieldVehiclePowertrainRange Remaining range in meters using all energy sources available in the vehicle.
	FieldVehiclePowertrainRange = "Vehicle_Powertrain_Range"
	// FieldVehiclePowertrainTractionBatteryChargingChargeLimit Target charge limit (state of charge) for battery.
	FieldVehiclePowertrainTractionBatteryChargingChargeLimit = "Vehicle_Powertrain_TractionBattery_Charging_ChargeLimit"
	// FieldVehiclePowertrainTractionBatteryChargingIsCharging True if charging is ongoing. Charging is considered to be ongoing if energy is flowing from charger to vehicle.
	FieldVehiclePowertrainTractionBatteryChargingIsCharging = "Vehicle_Powertrain_TractionBattery_Charging_IsCharging"
	// FieldVehiclePowertrainTractionBatteryGrossCapacity Gross capacity of the battery.
	FieldVehiclePowertrainTractionBatteryGrossCapacity = "Vehicle_Powertrain_TractionBattery_GrossCapacity"
	// FieldVehiclePowertrainTractionBatteryStateOfChargeCurrent Physical state of charge of the high voltage battery, relative to net capacity. This is not necessarily the state of charge being displayed to the customer.
	FieldVehiclePowertrainTractionBatteryStateOfChargeCurrent = "Vehicle_Powertrain_TractionBattery_StateOfCharge_Current"
	// FieldVehiclePowertrainTransmissionTravelledDistance Odometer reading, total distance travelled during the lifetime of the transmission.
	FieldVehiclePowertrainTransmissionTravelledDistance = "Vehicle_Powertrain_Transmission_TravelledDistance"
	// FieldVehiclePowertrainType Defines the powertrain type of the vehicle.
	FieldVehiclePowertrainType = "Vehicle_Powertrain_Type"
	// FieldVehicleSpeed Vehicle speed.
	FieldVehicleSpeed = "Vehicle_Speed"
	// FieldVehicleVehicleIdentificationBrand Vehicle brand or manufacturer.
	FieldVehicleVehicleIdentificationBrand = "Vehicle_VehicleIdentification_Brand"
	// FieldVehicleVehicleIdentificationModel Vehicle model.
	FieldVehicleVehicleIdentificationModel = "Vehicle_VehicleIdentification_Model"
	// FieldVehicleVehicleIdentificationYear Model year of the vehicle.
	FieldVehicleVehicleIdentificationYear = "Vehicle_VehicleIdentification_Year"
)

// JSONName2CHName maps the JSON field names to the Clickhouse column names.
var JSONName2CHName = map[string]string{
	"vehicleChassisAxleRow1WheelLeftTirePressure":          "Vehicle_Chassis_Axle_Row1_Wheel_Left_Tire_Pressure",
	"vehicleChassisAxleRow1WheelRightTirePressure":         "Vehicle_Chassis_Axle_Row1_Wheel_Right_Tire_Pressure",
	"vehicleChassisAxleRow2WheelLeftTirePressure":          "Vehicle_Chassis_Axle_Row2_Wheel_Left_Tire_Pressure",
	"vehicleChassisAxleRow2WheelRightTirePressure":         "Vehicle_Chassis_Axle_Row2_Wheel_Right_Tire_Pressure",
	"vehicleCurrentLocationAltitude":                       "Vehicle_CurrentLocation_Altitude",
	"vehicleCurrentLocationLatitude":                       "Vehicle_CurrentLocation_Latitude",
	"vehicleCurrentLocationLongitude":                      "Vehicle_CurrentLocation_Longitude",
	"vehicleCurrentLocationTimestamp":                      "Vehicle_CurrentLocation_Timestamp",
	"vehicleExteriorAirTemperature":                        "Vehicle_Exterior_AirTemperature",
	"vehicleLowVoltageBatteryCurrentVoltage":               "Vehicle_LowVoltageBattery_CurrentVoltage",
	"vehicleOBDBarometricPressure":                         "Vehicle_OBD_BarometricPressure",
	"vehicleOBDEngineLoad":                                 "Vehicle_OBD_EngineLoad",
	"vehicleOBDIntakeTemp":                                 "Vehicle_OBD_IntakeTemp",
	"vehicleOBDRunTime":                                    "Vehicle_OBD_RunTime",
	"vehiclePowertrainCombustionEngineECT":                 "Vehicle_Powertrain_CombustionEngine_ECT",
	"vehiclePowertrainCombustionEngineEngineOilLevel":      "Vehicle_Powertrain_CombustionEngine_EngineOilLevel",
	"vehiclePowertrainCombustionEngineSpeed":               "Vehicle_Powertrain_CombustionEngine_Speed",
	"vehiclePowertrainCombustionEngineTPS":                 "Vehicle_Powertrain_CombustionEngine_TPS",
	"vehiclePowertrainFuelSystemAbsoluteLevel":             "Vehicle_Powertrain_FuelSystem_AbsoluteLevel",
	"vehiclePowertrainFuelSystemSupportedFuelTypes":        "Vehicle_Powertrain_FuelSystem_SupportedFuelTypes",
	"vehiclePowertrainRange":                               "Vehicle_Powertrain_Range",
	"vehiclePowertrainTractionBatteryChargingChargeLimit":  "Vehicle_Powertrain_TractionBattery_Charging_ChargeLimit",
	"vehiclePowertrainTractionBatteryChargingIsCharging":   "Vehicle_Powertrain_TractionBattery_Charging_IsCharging",
	"vehiclePowertrainTractionBatteryGrossCapacity":        "Vehicle_Powertrain_TractionBattery_GrossCapacity",
	"vehiclePowertrainTractionBatteryStateOfChargeCurrent": "Vehicle_Powertrain_TractionBattery_StateOfCharge_Current",
	"vehiclePowertrainTransmissionTravelledDistance":       "Vehicle_Powertrain_Transmission_TravelledDistance",
	"vehiclePowertrainType":                                "Vehicle_Powertrain_Type",
	"vehicleSpeed":                                         "Vehicle_Speed",
	"vehicleVehicleIdentificationBrand":                    "Vehicle_VehicleIdentification_Brand",
	"vehicleVehicleIdentificationModel":                    "Vehicle_VehicleIdentification_Model",
	"vehicleVehicleIdentificationYear":                     "Vehicle_VehicleIdentification_Year",
}
