package vss

import (
	"fmt"
	"time"
)

// This file is automatically populated with conversion functions for each field of the model struct.
// any conversion functions already defined in this package will not be generated.
// Code generated by model-garage.

// ToVehicleChassisAxleRow1WheelLeftTirePressure0 converts data as float64 to float64.
func ToVehicleChassisAxleRow1WheelLeftTirePressure0(val float64) (float64, error) {
	return val, nil
}

// ToVehicleChassisAxleRow1WheelRightTirePressure0 converts data as float64 to float64.
func ToVehicleChassisAxleRow1WheelRightTirePressure0(val float64) (float64, error) {
	return val, nil
}

// ToVehicleChassisAxleRow2WheelLeftTirePressure0 converts data as float64 to float64.
func ToVehicleChassisAxleRow2WheelLeftTirePressure0(val float64) (float64, error) {
	return val, nil
}

// ToVehicleChassisAxleRow2WheelRightTirePressure0 converts data as float64 to float64.
func ToVehicleChassisAxleRow2WheelRightTirePressure0(val float64) (float64, error) {
	return val, nil
}

// ToVehicleCurrentLocationAltitude0 converts data as float64 to float64.
func ToVehicleCurrentLocationAltitude0(val float64) (float64, error) {
	return val, nil
}

// ToVehicleCurrentLocationLatitude0 converts data as float64 to float64.
func ToVehicleCurrentLocationLatitude0(val float64) (float64, error) {
	return val, nil
}

// ToVehicleCurrentLocationLongitude0 converts data as float64 to float64.
func ToVehicleCurrentLocationLongitude0(val float64) (float64, error) {
	return val, nil
}

// ToVehicleCurrentLocationTimestamp0 converts data as string to []time.Time.
func ToVehicleCurrentLocationTimestamp0(val string) (float64, error) {
	ts, err := time.Parse(time.RFC3339, val)
	if err != nil {
		return 0, fmt.Errorf("error parsing time: %w", err)
	}
	return float64(ts.UTC().Unix()), nil
}

// ToVehicleCurrentLocationTimestamp1 converts data as float64 to []time.Time.
func ToVehicleCurrentLocationTimestamp1(val float64) (float64, error) {
	return val, nil
}

// ToVehicleExteriorAirTemperature0 converts data as float64 to float64.
func ToVehicleExteriorAirTemperature0(val float64) (float64, error) {
	return val, nil
}

// ToVehicleLowVoltageBatteryCurrentVoltage0 converts data as float64 to float64.
func ToVehicleLowVoltageBatteryCurrentVoltage0(val float64) (float64, error) {
	return val, nil
}

// ToVehicleOBDBarometricPressure0 converts data as float64 to float64.
func ToVehicleOBDBarometricPressure0(val float64) (float64, error) {
	return val, nil
}

// ToVehicleOBDEngineLoad0 converts data as float64 to float64.
func ToVehicleOBDEngineLoad0(val float64) (float64, error) {
	return val, nil
}

// ToVehicleOBDIntakeTemp0 converts data as float64 to float64.
func ToVehicleOBDIntakeTemp0(val float64) (float64, error) {
	return val, nil
}

// ToVehicleOBDRunTime0 converts data as float64 to float64.
func ToVehicleOBDRunTime0(val float64) (float64, error) {
	return val, nil
}

// ToVehiclePowertrainCombustionEngineECT0 converts data as float64 to float64.
func ToVehiclePowertrainCombustionEngineECT0(val float64) (float64, error) {
	return val, nil
}

// ToVehiclePowertrainCombustionEngineEngineOilLevel0 converts data as float64 to any.
func ToVehiclePowertrainCombustionEngineEngineOilLevel0(oilLevel float64) (string, error) {
	switch {
	case oilLevel < 0.25:
		return "CRITICALLY_LOW", nil
	case oilLevel < 0.5:
		return "LOW", nil
	case oilLevel < 0.75:
		return "NORMAL", nil
	case oilLevel < .99:
		return "HIGH", nil
	default:
		return "CRITICALLY_HIGH", nil
	}
}

// ToVehiclePowertrainCombustionEngineSpeed0 converts data as float64 to float64.
func ToVehiclePowertrainCombustionEngineSpeed0(val float64) (float64, error) {
	return val, nil
}

// ToVehiclePowertrainCombustionEngineTPS0 converts data as float64 to float64.
func ToVehiclePowertrainCombustionEngineTPS0(val float64) (float64, error) {
	return val, nil
}

// ToVehiclePowertrainFuelSystemAbsoluteLevel0 converts data as float64 to float64.
func ToVehiclePowertrainFuelSystemAbsoluteLevel0(val float64) (float64, error) {
	return val, nil
}

// ToVehiclePowertrainFuelSystemSupportedFuelTypes0 converts data as string to any.
func ToVehiclePowertrainFuelSystemSupportedFuelTypes0(val string) (string, error) {
	switch val {
	case "Gasoline":
		return "GASOLINE", nil
	case "Ethanol":
		return "E85", nil
	case "Diesel":
		return "DIESEL", nil
	case "LPG":
		return "LPG", nil
	default:
		return "OTHER", nil
	}
}

// ToVehiclePowertrainRange0 converts data as float64 to float64.
func ToVehiclePowertrainRange0(val float64) (float64, error) {
	return val, nil
}

// ToVehiclePowertrainTractionBatteryChargingChargeLimit0 converts data as float64 to float64.
func ToVehiclePowertrainTractionBatteryChargingChargeLimit0(val float64) (float64, error) {
	return val, nil
}

// ToVehiclePowertrainTractionBatteryChargingIsCharging0 converts data as bool to float64.
func ToVehiclePowertrainTractionBatteryChargingIsCharging0(val bool) (float64, error) {
	if val {
		return 1, nil
	}
	return 0, nil
}

// ToVehiclePowertrainTractionBatteryGrossCapacity0 converts data as float64 to float64.
func ToVehiclePowertrainTractionBatteryGrossCapacity0(val float64) (float64, error) {
	return val, nil
}

// ToVehiclePowertrainTractionBatteryStateOfChargeCurrent0 converts data as float64 to float64.
func ToVehiclePowertrainTractionBatteryStateOfChargeCurrent0(val float64) (float64, error) {
	return val, nil
}

// ToVehiclePowertrainTransmissionTravelledDistance0 converts data as float64 to float64.
func ToVehiclePowertrainTransmissionTravelledDistance0(val float64) (float64, error) {
	return val, nil
}

// ToVehiclePowertrainType0 converts data as string to string.
func ToVehiclePowertrainType0(val string) (string, error) {
	// possible arguments Gasoline, Ethanol, Diesel, Not available, Electric, LPG
	// deault to combustion
	if val == "Electric" {
		return "ELECTRIC", nil
	}
	return "COMBUSTION", nil
}

// ToVehicleSpeed0 converts data as float64 to float64.
func ToVehicleSpeed0(val float64) (float64, error) {
	return val, nil
}

// ToVehicleVehicleIdentificationBrand0 converts data as string to string.
func ToVehicleVehicleIdentificationBrand0(val string) (string, error) {
	return val, nil
}

// ToVehicleVehicleIdentificationModel0 converts data as string to string.
func ToVehicleVehicleIdentificationModel0(val string) (string, error) {
	return val, nil
}

// ToVehicleVehicleIdentificationYear0 converts data as float64 to float64.
func ToVehicleVehicleIdentificationYear0(val float64) (float64, error) {
	return val, nil
}
