// Code generated by "model-garage" DO NOT EDIT.
package vss

import (
	"errors"
	"fmt"

	"github.com/tidwall/gjson"
)

var (
	// errInvalidType is returned when a field is not of the expected type or not found.
	errInvalidType = errors.New("invalid type")
)

// IsInvalidType returns true if the error is of type errInvalidType.
func IsInvalidType(err error) bool {
	return errors.Is(err, errInvalidType)
}

// FromData creates a new Dimo from a map of data. Using defined conversion functions.
// If skipNotFound is true, the function will not return an error if a key is not found.
// instead the field will be set to the zero value of the type.
func FromData(jsonData []byte) (*Dimo, error) {
	var dimo Dimo
	var errs error
	var err error
	var result gjson.Result

	// convert data.definitionID to DefinitionID
	result = gjson.GetBytes(jsonData, "data.definitionID")
	if result.Exists() {
		valDefinitionID, ok := result.Value().(string)
		if ok {
			dimo.DefinitionID, err = ToDefinitionID(valDefinitionID)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.definitionID': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.definitionID' is not of type 'string' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert source to Source
	result = gjson.GetBytes(jsonData, "source")
	if result.Exists() {
		valSource, ok := result.Value().(string)
		if ok {
			dimo.Source, err = ToSource(valSource)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'source': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'source' is not of type 'string' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert subject to Subject
	result = gjson.GetBytes(jsonData, "subject")
	if result.Exists() {
		valSubject, ok := result.Value().(string)
		if ok {
			dimo.Subject, err = ToSubject(valSubject)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'subject': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'subject' is not of type 'string' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert time to Timestamp
	result = gjson.GetBytes(jsonData, "time")
	if result.Exists() {
		valTimestamp, ok := result.Value().(string)
		if ok {
			dimo.Timestamp, err = ToTimestamp(valTimestamp)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'time': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'time' is not of type 'string' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert type to Type
	result = gjson.GetBytes(jsonData, "type")
	if result.Exists() {
		valType, ok := result.Value().(string)
		if ok {
			dimo.Type, err = ToType(valType)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'type': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'type' is not of type 'string' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.tires.frontLeft to VehicleChassisAxleRow1WheelLeftTirePressure
	result = gjson.GetBytes(jsonData, "data.tires.frontLeft")
	if result.Exists() {
		valVehicleChassisAxleRow1WheelLeftTirePressure, ok := result.Value().(float64)
		if ok {
			dimo.VehicleChassisAxleRow1WheelLeftTirePressure, err = ToVehicleChassisAxleRow1WheelLeftTirePressure(valVehicleChassisAxleRow1WheelLeftTirePressure)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.tires.frontLeft': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.tires.frontLeft' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.tires.frontRight to VehicleChassisAxleRow1WheelRightTirePressure
	result = gjson.GetBytes(jsonData, "data.tires.frontRight")
	if result.Exists() {
		valVehicleChassisAxleRow1WheelRightTirePressure, ok := result.Value().(float64)
		if ok {
			dimo.VehicleChassisAxleRow1WheelRightTirePressure, err = ToVehicleChassisAxleRow1WheelRightTirePressure(valVehicleChassisAxleRow1WheelRightTirePressure)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.tires.frontRight': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.tires.frontRight' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.tires.backLeft to VehicleChassisAxleRow2WheelLeftTirePressure
	result = gjson.GetBytes(jsonData, "data.tires.backLeft")
	if result.Exists() {
		valVehicleChassisAxleRow2WheelLeftTirePressure, ok := result.Value().(float64)
		if ok {
			dimo.VehicleChassisAxleRow2WheelLeftTirePressure, err = ToVehicleChassisAxleRow2WheelLeftTirePressure(valVehicleChassisAxleRow2WheelLeftTirePressure)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.tires.backLeft': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.tires.backLeft' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.tires.backRight to VehicleChassisAxleRow2WheelRightTirePressure
	result = gjson.GetBytes(jsonData, "data.tires.backRight")
	if result.Exists() {
		valVehicleChassisAxleRow2WheelRightTirePressure, ok := result.Value().(float64)
		if ok {
			dimo.VehicleChassisAxleRow2WheelRightTirePressure, err = ToVehicleChassisAxleRow2WheelRightTirePressure(valVehicleChassisAxleRow2WheelRightTirePressure)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.tires.backRight': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.tires.backRight' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.altitude to VehicleCurrentLocationAltitude
	result = gjson.GetBytes(jsonData, "data.altitude")
	if result.Exists() {
		valVehicleCurrentLocationAltitude, ok := result.Value().(float64)
		if ok {
			dimo.VehicleCurrentLocationAltitude, err = ToVehicleCurrentLocationAltitude(valVehicleCurrentLocationAltitude)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.altitude': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.altitude' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.latitude to VehicleCurrentLocationLatitude
	result = gjson.GetBytes(jsonData, "data.latitude")
	if result.Exists() {
		valVehicleCurrentLocationLatitude, ok := result.Value().(float64)
		if ok {
			dimo.VehicleCurrentLocationLatitude, err = ToVehicleCurrentLocationLatitude(valVehicleCurrentLocationLatitude)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.latitude': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.latitude' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.longitude to VehicleCurrentLocationLongitude
	result = gjson.GetBytes(jsonData, "data.longitude")
	if result.Exists() {
		valVehicleCurrentLocationLongitude, ok := result.Value().(float64)
		if ok {
			dimo.VehicleCurrentLocationLongitude, err = ToVehicleCurrentLocationLongitude(valVehicleCurrentLocationLongitude)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.longitude': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.longitude' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.timestamp to VehicleCurrentLocationTimestamp
	result = gjson.GetBytes(jsonData, "data.timestamp")
	if result.Exists() {
		valVehicleCurrentLocationTimestamp, ok := result.Value().(string)
		if ok {
			dimo.VehicleCurrentLocationTimestamp, err = ToVehicleCurrentLocationTimestamp(valVehicleCurrentLocationTimestamp)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.timestamp': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.timestamp' is not of type 'string' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.ambientTemp to VehicleExteriorAirTemperature
	result = gjson.GetBytes(jsonData, "data.ambientTemp")
	if result.Exists() {
		valVehicleExteriorAirTemperature, ok := result.Value().(float64)
		if ok {
			dimo.VehicleExteriorAirTemperature, err = ToVehicleExteriorAirTemperature(valVehicleExteriorAirTemperature)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.ambientTemp': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.ambientTemp' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.batteryVoltage to VehicleLowVoltageBatteryCurrentVoltage
	result = gjson.GetBytes(jsonData, "data.batteryVoltage")
	if result.Exists() {
		valVehicleLowVoltageBatteryCurrentVoltage, ok := result.Value().(float64)
		if ok {
			dimo.VehicleLowVoltageBatteryCurrentVoltage, err = ToVehicleLowVoltageBatteryCurrentVoltage(valVehicleLowVoltageBatteryCurrentVoltage)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.batteryVoltage': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.batteryVoltage' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.barometricPressure to VehicleOBDBarometricPressure
	result = gjson.GetBytes(jsonData, "data.barometricPressure")
	if result.Exists() {
		valVehicleOBDBarometricPressure, ok := result.Value().(float64)
		if ok {
			dimo.VehicleOBDBarometricPressure, err = ToVehicleOBDBarometricPressure(valVehicleOBDBarometricPressure)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.barometricPressure': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.barometricPressure' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.engineLoad to VehicleOBDEngineLoad
	result = gjson.GetBytes(jsonData, "data.engineLoad")
	if result.Exists() {
		valVehicleOBDEngineLoad, ok := result.Value().(float64)
		if ok {
			dimo.VehicleOBDEngineLoad, err = ToVehicleOBDEngineLoad(valVehicleOBDEngineLoad)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.engineLoad': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.engineLoad' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.intakeTemp to VehicleOBDIntakeTemp
	result = gjson.GetBytes(jsonData, "data.intakeTemp")
	if result.Exists() {
		valVehicleOBDIntakeTemp, ok := result.Value().(float64)
		if ok {
			dimo.VehicleOBDIntakeTemp, err = ToVehicleOBDIntakeTemp(valVehicleOBDIntakeTemp)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.intakeTemp': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.intakeTemp' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.runTime to VehicleOBDRunTime
	result = gjson.GetBytes(jsonData, "data.runTime")
	if result.Exists() {
		valVehicleOBDRunTime, ok := result.Value().(float64)
		if ok {
			dimo.VehicleOBDRunTime, err = ToVehicleOBDRunTime(valVehicleOBDRunTime)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.runTime': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.runTime' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.coolantTemp to VehiclePowertrainCombustionEngineECT
	result = gjson.GetBytes(jsonData, "data.coolantTemp")
	if result.Exists() {
		valVehiclePowertrainCombustionEngineECT, ok := result.Value().(float64)
		if ok {
			dimo.VehiclePowertrainCombustionEngineECT, err = ToVehiclePowertrainCombustionEngineECT(valVehiclePowertrainCombustionEngineECT)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.coolantTemp': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.coolantTemp' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.oil to VehiclePowertrainCombustionEngineEngineOilLevel
	result = gjson.GetBytes(jsonData, "data.oil")
	if result.Exists() {
		valVehiclePowertrainCombustionEngineEngineOilLevel, ok := result.Value().(float64)
		if ok {
			dimo.VehiclePowertrainCombustionEngineEngineOilLevel, err = ToVehiclePowertrainCombustionEngineEngineOilLevel(valVehiclePowertrainCombustionEngineEngineOilLevel)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.oil': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.oil' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.engineSpeed to VehiclePowertrainCombustionEngineSpeed
	result = gjson.GetBytes(jsonData, "data.engineSpeed")
	if result.Exists() {
		valVehiclePowertrainCombustionEngineSpeed, ok := result.Value().(float64)
		if ok {
			dimo.VehiclePowertrainCombustionEngineSpeed, err = ToVehiclePowertrainCombustionEngineSpeed(valVehiclePowertrainCombustionEngineSpeed)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.engineSpeed': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.engineSpeed' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.throttlePosition to VehiclePowertrainCombustionEngineTPS
	result = gjson.GetBytes(jsonData, "data.throttlePosition")
	if result.Exists() {
		valVehiclePowertrainCombustionEngineTPS, ok := result.Value().(float64)
		if ok {
			dimo.VehiclePowertrainCombustionEngineTPS, err = ToVehiclePowertrainCombustionEngineTPS(valVehiclePowertrainCombustionEngineTPS)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.throttlePosition': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.throttlePosition' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.fuelPercentRemaining to VehiclePowertrainFuelSystemAbsoluteLevel
	result = gjson.GetBytes(jsonData, "data.fuelPercentRemaining")
	if result.Exists() {
		valVehiclePowertrainFuelSystemAbsoluteLevel, ok := result.Value().(float64)
		if ok {
			dimo.VehiclePowertrainFuelSystemAbsoluteLevel, err = ToVehiclePowertrainFuelSystemAbsoluteLevel(valVehiclePowertrainFuelSystemAbsoluteLevel)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.fuelPercentRemaining': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.fuelPercentRemaining' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.fuelType to VehiclePowertrainFuelSystemSupportedFuelTypes
	result = gjson.GetBytes(jsonData, "data.fuelType")
	if result.Exists() {
		valVehiclePowertrainFuelSystemSupportedFuelTypes, ok := result.Value().(string)
		if ok {
			dimo.VehiclePowertrainFuelSystemSupportedFuelTypes, err = ToVehiclePowertrainFuelSystemSupportedFuelTypes(valVehiclePowertrainFuelSystemSupportedFuelTypes)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.fuelType': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.fuelType' is not of type 'string' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.range to VehiclePowertrainRange
	result = gjson.GetBytes(jsonData, "data.range")
	if result.Exists() {
		valVehiclePowertrainRange, ok := result.Value().(float64)
		if ok {
			dimo.VehiclePowertrainRange, err = ToVehiclePowertrainRange(valVehiclePowertrainRange)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.range': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.range' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.chargeLimit to VehiclePowertrainTractionBatteryChargingChargeLimit
	result = gjson.GetBytes(jsonData, "data.chargeLimit")
	if result.Exists() {
		valVehiclePowertrainTractionBatteryChargingChargeLimit, ok := result.Value().(float64)
		if ok {
			dimo.VehiclePowertrainTractionBatteryChargingChargeLimit, err = ToVehiclePowertrainTractionBatteryChargingChargeLimit(valVehiclePowertrainTractionBatteryChargingChargeLimit)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.chargeLimit': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.chargeLimit' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.charging to VehiclePowertrainTractionBatteryChargingIsCharging
	result = gjson.GetBytes(jsonData, "data.charging")
	if result.Exists() {
		valVehiclePowertrainTractionBatteryChargingIsCharging, ok := result.Value().(bool)
		if ok {
			dimo.VehiclePowertrainTractionBatteryChargingIsCharging, err = ToVehiclePowertrainTractionBatteryChargingIsCharging(valVehiclePowertrainTractionBatteryChargingIsCharging)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.charging': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.charging' is not of type 'bool' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.batteryCapacity to VehiclePowertrainTractionBatteryGrossCapacity
	result = gjson.GetBytes(jsonData, "data.batteryCapacity")
	if result.Exists() {
		valVehiclePowertrainTractionBatteryGrossCapacity, ok := result.Value().(float64)
		if ok {
			dimo.VehiclePowertrainTractionBatteryGrossCapacity, err = ToVehiclePowertrainTractionBatteryGrossCapacity(valVehiclePowertrainTractionBatteryGrossCapacity)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.batteryCapacity': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.batteryCapacity' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.soc to VehiclePowertrainTractionBatteryStateOfChargeCurrent
	result = gjson.GetBytes(jsonData, "data.soc")
	if result.Exists() {
		valVehiclePowertrainTractionBatteryStateOfChargeCurrent, ok := result.Value().(float64)
		if ok {
			dimo.VehiclePowertrainTractionBatteryStateOfChargeCurrent, err = ToVehiclePowertrainTractionBatteryStateOfChargeCurrent(valVehiclePowertrainTractionBatteryStateOfChargeCurrent)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.soc': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.soc' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.odometer to VehiclePowertrainTransmissionTravelledDistance
	result = gjson.GetBytes(jsonData, "data.odometer")
	if result.Exists() {
		valVehiclePowertrainTransmissionTravelledDistance, ok := result.Value().(float64)
		if ok {
			dimo.VehiclePowertrainTransmissionTravelledDistance, err = ToVehiclePowertrainTransmissionTravelledDistance(valVehiclePowertrainTransmissionTravelledDistance)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.odometer': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.odometer' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.fuelType to VehiclePowertrainType
	result = gjson.GetBytes(jsonData, "data.fuelType")
	if result.Exists() {
		valVehiclePowertrainType, ok := result.Value().(string)
		if ok {
			dimo.VehiclePowertrainType, err = ToVehiclePowertrainType(valVehiclePowertrainType)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.fuelType': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.fuelType' is not of type 'string' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.speed to VehicleSpeed
	result = gjson.GetBytes(jsonData, "data.speed")
	if result.Exists() {
		valVehicleSpeed, ok := result.Value().(float64)
		if ok {
			dimo.VehicleSpeed, err = ToVehicleSpeed(valVehicleSpeed)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.speed': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.speed' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.make to VehicleVehicleIdentificationBrand
	result = gjson.GetBytes(jsonData, "data.make")
	if result.Exists() {
		valVehicleVehicleIdentificationBrand, ok := result.Value().(string)
		if ok {
			dimo.VehicleVehicleIdentificationBrand, err = ToVehicleVehicleIdentificationBrand(valVehicleVehicleIdentificationBrand)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.make': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.make' is not of type 'string' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.model to VehicleVehicleIdentificationModel
	result = gjson.GetBytes(jsonData, "data.model")
	if result.Exists() {
		valVehicleVehicleIdentificationModel, ok := result.Value().(string)
		if ok {
			dimo.VehicleVehicleIdentificationModel, err = ToVehicleVehicleIdentificationModel(valVehicleVehicleIdentificationModel)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.model': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.model' is not of type 'string' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.year to VehicleVehicleIdentificationYear
	result = gjson.GetBytes(jsonData, "data.year")
	if result.Exists() {
		valVehicleVehicleIdentificationYear, ok := result.Value().(float64)
		if ok {
			dimo.VehicleVehicleIdentificationYear, err = ToVehicleVehicleIdentificationYear(valVehicleVehicleIdentificationYear)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.year': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.year' is not of type 'float64' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}

	// convert data.vehicleID to VehicleID
	result = gjson.GetBytes(jsonData, "data.vehicleID")
	if result.Exists() {
		valVehicleID, ok := result.Value().(string)
		if ok {
			dimo.VehicleID, err = ToVehicleID(valVehicleID)
			if err != nil {
				errs = errors.Join(errs, fmt.Errorf("failed to convert 'data.vehicleID': %w", err))
			}
		} else {
			errs = errors.Join(errs, fmt.Errorf("%w, field 'data.vehicleID' is not of type 'string' got '%v' of type '%T'", errInvalidType, result.Value(), result.Value()))
		}
	}
	return &dimo, errs
}
