// Code generated by "model-garage" DO NOT EDIT.
package vss

import (
	_ "embed"
)

// Dimo is the SQL query to create a clickhouse table for the Dimo model.
//
//go:embed dimo-gql.graphql
var DimoGraphSchema string
